version: '3.3'
services:
#    gaara:
#        container_name: gaara
#        restart: unless-stopped
#        network_mode: host
#        volumes:
#          - '/mnt/Storage6TB/appsmount/gaara/www:/app'
#          - '/mnt/Storage6TB/appsmount/gaara/etc:/opt/docker/etc'
#          - '/mnt/Storage6TB/appsmount/gaara/ports.conf:/etc/apache2/ports.conf'
#        image: webdevops/php-apache:latest

#    ferus:
#        container_name: ferus
#        restart: unless-stopped
#        network_mode: host
#        volumes:
#          - '/mnt/Storage6TB/appsmount/ferus/www:/app'
#          - '/mnt/Storage6TB/appsmount/ferus/etc:/opt/docker/etc'
#          - '/mnt/Storage6TB/appsmount/ferus/ports.conf:/etc/apache2/ports.conf'
#        image: webdevops/php-apache:latest


    wiki:
      container_name: willwiki
      image: requarks/wiki:2
      environment:
        DB_TYPE: mariadb
        DB_HOST: mirai.eirikzlab.local
        DB_PORT: 13306
        DB_USER: ${WILLWIKIDBUSER}
        DB_PASS: ${WILLWIKIDBPASS}
        DB_NAME: ${WILLWIKIDBNAME}
      restart: unless-stopped
#      ports:
#        - "3588:3000"
      network_mode: host
      volumes:
        - '/mnt/Storage6TB/appsmount/willwiki/config.yml:/wiki/config.yml'
      logging:
        driver: "gelf"
        options:
          gelf-address: "udp://mirai.eirikzlab.local:12201"


    madara:
        container_name: madara
        environment:
            - TZ=Europe/Oslo
            - URL=${MADARAURL}
            - SUBDOMAINS=${MADARASUBDOMAINS}
            - VALIDATION=${MADARAVALIDATION}
            - DNSPLUGIN=${MADARADNSPLUGIN}
            - EMAIL=${MADARAEMAIL}
            - DHLEVEL=${MADARADHLEVEL}
            - STAGING=${MADARASTAGING}
            - DOCKER_MODS=linuxserver/mods:universal-stdout-logs
            - LOGS_TO_STDOUT=/config/log/nginx/access.log|/config/log/nginx/error.log
        network_mode: host
        volumes:
            - '/mnt/Storage6TB/appsmount/madara:/config'
        restart: unless-stopped
        image: linuxserver/swag
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12401"

    authelia:
      image: authelia/authelia:4.21.0
      container_name: authelia
      environment:
        - TZ=Europe/Oslo
      volumes:
        - /mnt/Storage6TB/appsmount/authelia:/config
      restart: unless-stopped
      network_mode: host



    naruto:
        container_name: naruto
        network_mode: host
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=${NARUTOMYSQLPASSWORD}
        volumes:
          - '/mnt/Storage6TB/appsmount/naruto:/var/lib/mysql'
          - '/mnt/Storage6TB/appsmount/naruto/config/my.cnf:/etc/mysql/my.cnf'
        image: mariadb:10.5
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"



    nextcloud:
        container_name: nextcloud
        network_mode: host
        restart: unless-stopped
        environment:
          - PUID=911
          - PGID=998
          - TZ=Europe/Oslo
        volumes:
          - '/mnt/Storage6TB/appsmount/nextcloud/data:/data'
          - '/mnt/Storage6TB/appsmount/nextcloud/config:/config'
          - '/mnt/Storage/Felles-Owncloud:/mnt/felles'
          - '/mnt/Storage/eirikz:/mnt/eirikz'
          - '/mnt/Storage/weronica:/mnt/weronica'
        image: ghcr.io/linuxserver/nextcloud
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"



    netbootxyz:
        container_name: netbootxyz
        network_mode: host
        restart: unless-stopped
        volumes:
          - '/mnt/Storage6TB/appsmount/netbootxyz/config:/config'
          - '/mnt/Storage6TB/appsmount/netbootxyz/assets:/assets'
        image: ghcr.io/linuxserver/netbootxyz
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"


    vaultwarden:
        container_name: vaultwarden
        network_mode: host
        restart: unless-stopped
        environment:
          - SIGNUPS_ALLOWED=false
          - ADMIN_TOKEN=${VAULTWARDENADMINTOKEN}
          - YUBICO_CLIENT_ID=${VAULTWARDENYUBICOCLIENTID}
          - YUBICO_SECRET_KEY=${VAULTWARDENYUBICOSECRETKEY}
          - ROCKET_PORT=9843
        volumes:
          - '/mnt/Storage6TB/appsmount/vaultwarden:/data'
        image: vaultwarden/server:latest
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"




    mongodb:
      container_name: mongodb
      ports:
        - 27017:27017
      image: mongo:4.2
      volumes:
         - /mnt/Storage6TB/appsmount/mongodb:/data/db
      logging:
        driver: "gelf"
        options:
          gelf-address: "udp://mirai.eirikzlab.local:12201"


    elasticsearch:
      container_name: elastisearch
      ports:
        - 9200:9200
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
      volumes: 
        - /mnt/Storage6TB/appsmount/elastisearch:/usr/share/elasticsearch/data
      logging:
        driver: "gelf"
        options:
          gelf-address: "udp://mirai.eirikzlab.local:12201"


    graylog:
      container_name: graylog
      image: graylog/graylog:4.2
      environment:
        - GRAYLOG_PASSWORD_SECRET=${GRAYLOGPASSWORDSECRET}
        - GRAYLOG_ROOT_PASSWORD_SHA2=$GRAYLOGROOTPASSWORDSHA2}
        - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.1.11:9500/
      entrypoint: /usr/bin/tini -- wait-for-it 192.168.1.11:9200 --  /docker-entrypoint.sh
      restart: always
      network_mode: host
      volumes:
        - /mnt/Storage6TB/appsmount/graylog/journal:/usr/share/graylog/data/journal
        - /mnt/Storage6TB/appsmount/graylog/config:/usr/share/graylog/data/config
      logging:
        driver: "gelf"
        options:
          gelf-address: "udp://mirai.eirikzlab.local:12201"
