version: '3.3'
services:

    youtransfer:
        container_name: youtransfer
        network_mode: host
        volumes:
          - '/mnt/Storage6TB/appsmount/youtransfer:/opt/youtransfer/config'
          - '/mnt/Storage6TB/appsmount/youtransfer:/opt/youtransfer/uploads'
        restart: unless-stopped
        image: remie/youtransfer:stable

    gaara:
        container_name: gaara
        restart: unless-stopped
        volumes:
          - '/mnt/Storage6TB/appsmount/gaara/www:/app'
          - '/mnt/Storage6TB/appsmount/gaara/etc:/opt/docker/etc'
        image: webdevops/php-apache:latest


    motion:
        container_name: motion
        network_mode: host
        environment:
          - TZ=Europe/Oslo
        volumes: 
          - '/mnt/Storage6TB/appsmount/motion/config:/etc/motioneye'
          - '/mnt/Storage6TB/appsmount/motion/storage:/var/lib/motioneye'
          - '/etc/localtime:/etc/localtime:ro'
        restart: unless-stopped
        image: ccrisan/motioneye:master-amd64

    madara:
        container_name: madara
        environment:
            - TZ=Europe/Oslo
            - URL=${MADARAURL}
            - SUBDOMAINS=${MADARASUBDOMAINS}
            - VALIDATION=${MADARAVALIDATION}
            - DNSPLUGIN=${MADARADNSPLUGIN}
            - EMAIL=${MADARAEMAIL}
            - DHLEVEL=${MADARADHLEVEL}
            - STAGING=${MADARASTAGING}
        network_mode: host
        volumes:
            - '/mnt/Storage6TB/appsmount/madara:/config'
        restart: unless-stopped
        image: linuxserver/swag


    naruto:
        container_name: naruto
        network_mode: host
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=${NARUTOMYSQLPASSWORD}
        volumes:
          - '/mnt/Storage6TB/appsmount/naruto:/var/lib/mysql'
          - '/mnt/Storage6TB/appsmount/naruto/config/my.cnf:/etc/mysql/my.cnf'
        image: mariadb:latest

    nextcloud:
        container_name: nextcloud
        network_mode: host
        restart: unless-stopped
        environment:
          - PUID=911
          - PGID=998
          - TZ=Europe/Oslo
        volumes:
          - '/mnt/Storage6TB/appsmount/nextcloud/data:/data'
          - '/mnt/Storage6TB/appsmount/nextcloud/config:/config'
          - '/mnt/Storage/Felles-Owncloud:/mnt/felles'
          - '/mnt/Storage/eirikz:/mnt/eirikz'
          - '/mnt/Storage/weronica:/mnt/weronica'
        image: ghcr.io/linuxserver/nextcloud

    netbootxyz:
        container_name: netbootxyz
        network_mode: host
        restart: unless-stopped
        volumes:
          - '/mnt/Storage6TB/appsmount/netbootxyz/config:/config'
          - '/mnt/Storage6TB/appsmount/netbootxyz/assets:/assets'
        image: ghcr.io/linuxserver/netbootxyz


### NOT MIGRATED TO NEW DOCKER HOST YET
version: '3.3'
services:
    idrac:
        container_name: idrac
        ports:
          - '5800:5800'
          - '5900:5900'
        restart: unless-stopped
        environment:
          - IDRAC_HOST=192.168.1.253
          - IDRAC_USER=username
          - IDRAC_PASSWORD=password
          - USER_ID=0
          - GROUP_ID=0

        volumes:
          - '/dockerssd/idrac/app:/app'
          - '/dockerssd/idrac/vmedia:/vmedia'
          - '/dockerssd/idrac/screenshots:/screenshots'
        image: domistyle/idrac6

    netbootxyz:
        container_name: netbootxyz
        ports:
          - '3004:3004/tcp'
          - '69:69/udp'
          - '8080:80/tcp'
        restart: unless-stopped
        volumes:
          - '/dockerssd/xyz/config:/config'
          - '/dockerssd/xyz/assets:/assets'
        image: ghcr.io/linuxserver/netbootxyz

    bitwardenrs:
        container_name: bitwardenrs
        ports:
          - '80:80/tcp'
        restart: unless-stopped
        environment:
          - SIGNUPS_ALLOWED=false
          - ADMIN_TOKEN=mysecrettoken
          - YUBICO_CLIENT_ID=123456
          - YUBICO_SECRET_KEY=yubicosecret
        volumes:
          - '/dockerssd/bitwarden:/data'
        image: bitwardenrs/server:latest

    protonmail-bridge:
        container_name: protonmail-bridge
        volumes:
            - '/dockerssd/protonmailbridge:/root'
        ports:
            - '1025:25/tcp'
            - '1143:143/tcp'
        restart: unless-stopped
        image: 'shenxn/protonmail-bridge:latest


    ipmitomqtt:
      container_name: ipmitomqtt
      image: ipmi2mqtt:latest
      environment:
        - IPMIHOST=192.168.1.253
        - IPMIUSER=user
        - IPMIPASS=password
        - IPMIVARIABLE1=lanplus
        - IPMIVARIABLE2=sdr
        - IPMIGREP=Level
        - IPMICUT=20-22
        - MOSQUITTOHOST=192.168.1.40
        - MOSQUITTOUSER=user
        - MOSQUITTOPASS=password
        - MOSQUITTOTOPIC=idracpower
        - IPMIFILE=/tmp/power

    octoprint:
      container_name: octoprint
      image: octoprint/octoprint
      restart: unless-stopped
      ports:
        - '5000:80'
      devices:
        - '/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0'
      volumes:
       - '/dockerssd/octoprint:/octoprint/octoprint'
       - '/dockerssd/octoprint/plugins:/octoprint/plugins
