version: '3.3'
services:
    grafana:
        container_name: grafana
        network_mode: host
        restart: unless-stopped
        volumes:
          - '/mnt/Storage6TB/appsmount/grafana:/var/lib/grafana'
        environment: 
          - 'GF_SERVER_HTTP_PORT=9700'
        image: grafana/grafana
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"


    esphome:
        container_name: kiba
        environment:
          - ESPHOME_DASHBOARD_USE_PING="true"
        network_mode: host
        restart: unless-stopped
        volumes:
          - '/mnt/Storage6TB/appsmount/esphome:/config'
        image: esphome/esphome
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"



    mosquitto:
        container_name: shino
        network_mode: host
        volumes:
          - /mnt/Storage6TB/appsmount/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
          - /mnt/Storage6TB/appsmount/mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
          - /mnt/Storage6TB/appsmount/mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
          - /mnt/Storage6TB/appsmount/mosquitto/data:/mosquitto/data
          - /mnt/Storage6TB/appsmount/mosquitto/mosquitto.pid:/var/run/mosquitto.pid
        restart: unless-stopped
        image: eclipse-mosquitto
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"



    tasmoadmin:
       container_name: choji
       network_mode: host
       volumes:
         - /mnt/Storage6TB/appsmount/tasmoadmin:/data
       restart: unless-stopped
       image: raymondmm/tasmoadmin
       logging:
         driver: "gelf"
         options:
           gelf-address: "udp://mirai.eirikzlab.local:12201"



    influxdb:
        container_name: tenten
        network_mode: host
        volumes:
          - '/mnt/Storage6TB/appsmount/influxdb:/var/lib/influxdb'
        environment:
          - INFLUXDB_DB=${INFLUXDBDBNAME}
          - INFLUXDB_HTTP_AUTH_ENABLED=true
          - INFLUXDB_ADMIN_USER=${INFLUXDBADMINUSER}
          - INFLUXDB_ADMIN_PASSWORD=$INFLUXDBADMINPASSWORD}
        restart: unless-stopped
        image: influxdb
        logging:
          driver: "gelf"
          options:
            gelf-address: "udp://mirai.eirikzlab.local:12201"



    neji:
      container_name: neji
      volumes:
          - '/mnt/Storage6TB/appsmount/neji:/app/data'
      network_mode: host
      environment:
           - TZ=Europe/Oslo
      restart: unless-stopped
      image: 'koenkk/zigbee2mqtt:latest-dev'
      logging:
        driver: "gelf"
        options:
          gelf-address: "udp://mirai.eirikzlab.local:12201"
